<?php
/**
 * Language Helper
 * Helper untuk menangani multi-bahasa (Indonesia & English)
 */

if (!function_exists('lang_text')) {
    /**
     * Get translated text based on current language session
     * @param string $key - Key for the translation
     * @return string - Translated text
     */
    function lang_text($key) {
        $CI =& get_instance();
        $lang = $CI->session->userdata('bahasa') ?? 'id';
        
        $translations = get_translations();
        
        if (isset($translations[$lang][$key])) {
            return $translations[$lang][$key];
        }
        
        // Fallback to Indonesian
        if (isset($translations['id'][$key])) {
            return $translations['id'][$key];
        }
        
        // Return key if no translation found
        return $key;
    }
}

if (!function_exists('get_translations')) {
    /**
     * Get all translations array
     * @return array
     */
    function get_translations() {
        return [
            'id' => [
                // General
                'save' => 'Simpan',
                'cancel' => 'Batal',
                'edit' => 'Edit',
                'delete' => 'Hapus',
                'add' => 'Tambah',
                'search' => 'Cari',
                'loading' => 'Memuat...',
                'success' => 'Berhasil',
                'error' => 'Gagal',
                'warning' => 'Peringatan',
                'confirm' => 'Konfirmasi',
                'yes' => 'Ya',
                'no' => 'Tidak',
                'view_all' => 'Lihat Semua',
                'filter' => 'Filter',
                'export' => 'Ekspor',
                'print' => 'Cetak',
                'download' => 'Unduh',
                'back' => 'Kembali',
                'next' => 'Selanjutnya',
                'previous' => 'Sebelumnya',
                'detail' => 'Detail',
                'view' => 'Lihat',
                'close' => 'Tutup',
                'date' => 'Tanggal',
                'time' => 'Waktu',
                'month' => 'Bulan',
                'year' => 'Tahun',
                'total' => 'Total',
                'amount' => 'Jumlah',
                'price' => 'Harga',
                'quantity' => 'Kuantitas',
                'description' => 'Deskripsi',
                'notes' => 'Catatan',
                'address' => 'Alamat',
                'active' => 'Aktif',
                
                // Sidebar Menu
                'dashboard' => 'Dashboard',
                'orders' => 'Pesanan',
                'inventory' => 'Inventori',
                'customers' => 'Pelanggan',
                'finance' => 'Keuangan',
                'recommendations' => 'Rekomendasi',
                'settings' => 'Pengaturan',
                'logout' => 'Keluar',
                
                // Dashboard Page
                'welcome_back' => 'Selamat Datang Kembali',
                'total_revenue' => 'Total Pendapatan',
                'total_orders' => 'Total Pesanan',
                'total_orders_today' => 'Total Pesanan Hari ini',
                'monthly_revenue' => 'Pendapatan Bulanan',
                'from_last_month' => 'dari bulan lalu',
                'active_customers' => 'Pelanggan Aktif',
                'pending_pickups' => 'Menunggu Diambil',
                'requires_attention' => 'Butuh perhatian',
                'branch_performance' => 'Performa Cabang',
                'customer_volume_service' => 'Volume Pelanggan Per Layanan',
                'monthly_revenue_trend' => 'Tren Pendapatan Bulanan',
                'service_distribution' => 'Distribusi Layanan',
                'recommendation' => 'Rekomendasi',
                'view_details' => 'Lihat Detail',
                'total_customers' => 'Total Pelanggan',
                'total_products' => 'Total Produk',
                'recent_orders' => 'Pesanan Terbaru',
                'no_recent_orders' => 'Belum ada pesanan terbaru',
                'customer' => 'Pelanggan',
                'service' => 'Layanan',
                'revenue_chart' => 'Grafik Pendapatan',
                'today' => 'Hari ini',
                'this_week' => 'Minggu ini',
                'this_month' => 'Bulan ini',
                'this_year' => 'Tahun ini',
                'order_id' => 'ID Pesanan',
                'customer_name' => 'Nama Pelanggan',
                'notifications_alerts' => 'Notifikasi & Peringatan',
                'mark_all_read' => 'Tandai Semua Dibaca',
                'quick_actions' => 'Aksi Cepat',
                'add_order' => 'Tambah Pesanan',
                'add_customer' => 'Tambah Pelanggan',
                
                // Orders Page
                'order_list' => 'Daftar Pesanan',
                'new_order' => 'Pesanan Baru',
                'order_status' => 'Status Pesanan',
                'pending' => 'Menunggu',
                'processing' => 'Diproses',
                'completed' => 'Selesai',
                'cancelled' => 'Dibatalkan',
                'order_date' => 'Tanggal Pesanan',
                'delivery_date' => 'Tanggal Pengiriman',
                'payment_status' => 'Status Pembayaran',
                'paid' => 'Lunas',
                'unpaid' => 'Belum Bayar',
                'partial' => 'Sebagian',
                
                // Inventory Page
                'manage_inventory' => 'Kelola Inventory',
                'product_list' => 'Daftar Produk',
                'add_product' => 'Tambah Produk',
                'product_name' => 'Nama Produk',
                'item_id' => 'ID Item',
                'item_name' => 'Nama Item',
                'stock' => 'Stok',
                'stock_qty' => 'Jumlah Stok',
                'unit' => 'Satuan',
                'last_stock' => 'Stok Terakhir',
                'supplier' => 'Supplier',
                'low_stock' => 'Stok Menipis',
                'out_of_stock' => 'Stok Habis',
                'available' => 'Tersedia',
                'category' => 'Kategori',
                'all_categories' => 'Semua Kategori',
                'material' => 'Bahan',
                'tools' => 'Alat',
                'supplies' => 'Perlengkapan',
                'top_item_usage' => 'Top Penggunaan Item',
                'inventory_by_category' => 'Inventory Per Kategori',
                'stock_trend' => 'Tren Jumlah Stok',
                'sku' => 'SKU',
                'cost_price' => 'Harga Beli',
                'selling_price' => 'Harga Jual',
                'stock_alert' => 'Peringatan Stok',
                'no_inventory_data' => 'Tidak ada data inventory',
                
                // Customers Page
                'customer_list' => 'Daftar Pelanggan',
                'add_customer' => 'Tambah Pelanggan',
                'customer_id' => 'ID Pelanggan',
                'total_transactions' => 'Total Transaksi',
                'last_order' => 'Pesanan Terakhir',
                'customer_since' => 'Pelanggan Sejak',
                
                // Finance Page
                'financial_report' => 'Laporan Keuangan',
                'income' => 'Pemasukan',
                'expense' => 'Pengeluaran',
                'profit' => 'Keuntungan',
                'loss' => 'Kerugian',
                'balance' => 'Saldo',
                'transaction_history' => 'Riwayat Transaksi',
                'total_income' => 'Total Pemasukan',
                'total_expense' => 'Total Pengeluaran',
                'net_profit' => 'Net Profit',
                'current_period' => 'Periode Saat Ini',
                'transactions' => 'Transaksi',
                'cash_flow_trend' => 'Tren Cash Flow',
                'expense_breakdown' => 'Rincian Pengeluaran',
                'cost_details' => 'Rincian Biaya',
                'add_transaction' => 'Tambah Transaksi',
                'add_income' => 'Tambah Pemasukan',
                'add_expense' => 'Tambah Pengeluaran',
                'export_data' => 'Export Data',
                'report_type' => 'Tipe Laporan',
                'all_transactions' => 'Semua Transaksi',
                'income_only' => 'Pemasukan Saja',
                'expense_only' => 'Pengeluaran Saja',
                'other_format' => 'Format Lainnya',
                'for_print' => 'Untuk Cetak',
                'filter_finance' => 'Filter Keuangan',
                'apply_filter' => 'Terapkan Filter',
                'reset' => 'Reset',
                'all_branches' => 'Semua Cabang',
                'all_months' => 'Semua Bulan',
                'transaction_name' => 'Nama Transaksi',
                'type' => 'Tipe',
                'no_transaction_data' => 'Tidak ada data transaksi',
                'transaction_proof' => 'Bukti Transaksi',
                
                // Customer Page
                'manage_customers' => 'Kelola Pelanggan',
                'total_customers' => 'Total Pelanggan',
                'active_customers' => 'Pelanggan Aktif',
                'new_this_month' => 'Baru Bulan Ini',
                'all_time' => 'Semua Waktu',
                'last_30_days' => '30 Hari Terakhir',
                'distribution_by_branch' => 'Distribusi Per Cabang',
                'top_active_customers' => 'Top 5 Pelanggan Aktif',
                'monthly_growth' => 'Pertumbuhan Bulanan',
                'customer_data' => 'Data Pelanggan',
                'add_customer' => 'Tambah Pelanggan',
                'search_customer' => 'Cari pelanggan...',
                'total_orders' => 'Total Pesanan',
                'add_new_customer' => 'Tambah Pelanggan Baru',
                'customer_details' => 'Detail Pelanggan',
                'confirm_delete' => 'Konfirmasi Hapus',
                'confirm_delete_customer' => 'Apakah Anda yakin ingin menghapus pelanggan:',
                'no_customer_data' => 'Tidak ada data pelanggan',
                'months_6' => '6 Bulan',
                'months_3' => '3 Bulan',
                'months_12' => '12 Bulan',
                
                // Orders Page
                'manage_orders' => 'Kelola Pesanan',
                'order_list' => 'Daftar Pesanan',
                'new_order' => 'Pesanan Baru',
                'pending_orders' => 'Pesanan Pending',
                'in_process' => 'Dalam Proses',
                'ready_pickup' => 'Siap Diambil',
                'order_details' => 'Detail Pesanan',
                'order_date' => 'Tanggal Pesanan',
                'pickup_date' => 'Tanggal Ambil',
                'service_type' => 'Jenis Layanan',
                'shoe_type' => 'Jenis Sepatu',
                'shoe_brand' => 'Merek Sepatu',
                'order_notes' => 'Catatan Pesanan',
                'update_status' => 'Update Status',
                'print_invoice' => 'Cetak Invoice',
                'no_order_data' => 'Tidak ada data pesanan',
                'order_data' => 'Data Pesanan',
                'order_number' => 'Nomor Pesanan',
                'order_trend' => 'Tren Pesanan',
                'orders_by_branch' => 'Pesanan per Cabang',
                'orders_completed' => 'Pesanan Selesai',
                'received' => 'Diterima',
                'cancelled' => 'Dibatalkan',
                'quick_insights' => 'Insight Ringkas',
                'days' => 'Hari',
                'all_status' => 'Semua Status',
                'will_be_deleted' => 'akan dihapus secara permanen',
                
                // Recommendations Page
                'ai_recommendations' => 'Rekomendasi AI',
                'product_recommendations' => 'Rekomendasi Produk',
                'sales_insights' => 'Wawasan Penjualan',
                'inventory_suggestions' => 'Saran Inventori',
                
                // Settings Page
                'profile_settings' => 'Pengaturan Profile',
                'manage_profile_preferences' => 'Kelola profil dan preferensi akun Anda',
                'full_name' => 'Nama Lengkap',
                'email' => 'Email',
                'phone' => 'Telepon',
                'password' => 'Password',
                'change_password' => 'Ubah Password',
                'change_photo' => 'Ubah Foto',
                'save_changes' => 'Simpan Perubahan',
                
                // Employee Management
                'manage_employees' => 'Kelola Akun Karyawan',
                'manage_employees_desc' => 'Tambahkan dan kelola akun staf untuk cabang Anda',
                'add_employee' => 'Tambah Akun Karyawan',
                'employee_id' => 'ID Karyawan',
                'employee_name' => 'Nama Karyawan',
                'position' => 'Jabatan',
                'branch' => 'Cabang',
                'status' => 'Status',
                'action' => 'Aksi',
                'active' => 'Aktif',
                'inactive' => 'Nonaktif',
                
                // Branch Management
                'manage_branches' => 'Kelola Cabang Bisnis',
                'add_branch' => 'Tambah Cabang',
                'branch_name' => 'Nama Cabang',
                'address' => 'Alamat',
                
                // Notification Settings
                'notification_settings' => 'Pengaturan Notifikasi',
                'order_updates' => 'Update Pesanan',
                'order_updates_desc' => 'Dapatkan pemberitahuan saat pesanan dilakukan atau diperbarui',
                'inventory_stock' => 'Stok Inventory',
                'inventory_stock_desc' => 'Dapatkan alert saat stok barang menipis',
                'daily_report' => 'Laporan Harian',
                'daily_report_desc' => 'Terima ringkasan laporan harian via email',
                
                // System Preferences
                'system_preferences' => 'Preferensi Sistem',
                'language' => 'Bahasa',
                'currency' => 'Mata Uang',
                'save_preferences' => 'Simpan Preferensi',
                
                // Subscription
                'upgrade_subscription' => 'Upgrade Langganan',
                'upgrade_desc' => 'Aktifkan fitur premium untuk meningkatkan bisnis Anda',
                'current_plan' => 'Plan saat ini',
                'view_packages' => 'Lihat Paket',
                
                // Subscription Page
                'choose_subscription' => 'Pilih Paket Langganan',
                'upgrade_business' => 'Tingkatkan bisnis Anda dengan fitur premium',
                'active_plan' => 'Paket Aktif',
                'valid_until' => 'Berlaku hingga',
                'free_plan' => 'Free',
                'pro_plan' => 'Pro',
                'premium_plan' => 'Premium',
                'free_forever' => 'Gratis Selamanya',
                'per_month' => 'Bulan',
                'perfect_small_business' => 'Cocok untuk bisnis kecil',
                'ideal_growing_business' => 'Ideal untuk bisnis berkembang',
                'for_enterprise' => 'Untuk bisnis enterprise',
                'most_popular' => 'Paling Populer',
                'get_started' => 'Mulai Sekarang',
                'up_to_orders' => 'Hingga {0} pesanan/bulan',
                'orders_100' => 'Hingga 100 pesanan/bulan',
                'orders_10000' => 'Hingga 10.000 pesanan/bulan',
                'unlimited_orders' => 'Pesanan unlimited',
                'basic_inventory' => 'Tracking inventaris dasar',
                'email_support' => 'Dukungan email',
                'advanced_analytics' => 'Analitik lanjutan',
                'ai_recommendations' => 'Rekomendasi AI',
                'priority_support' => 'Dukungan prioritas',
                'custom_integrations' => 'Integrasi kustom',
                'multi_location' => 'Dukungan multi-lokasi',
                'phone_support_24_7' => 'Dukungan telepon 24/7',
                
                // FAQ Section
                'faq_title' => 'Pertanyaan Umum',
                'faq_upgrade_q' => 'Bagaimana cara upgrade paket?',
                'faq_upgrade_a' => 'Klik tombol upgrade pada paket yang Anda inginkan, lalu ikuti proses pembayaran. Langganan akan aktif segera setelah pembayaran berhasil.',
                'faq_downgrade_q' => 'Apakah bisa downgrade paket?',
                'faq_downgrade_a' => 'Ya, Anda bisa downgrade kapan saja. Perubahan akan berlaku di periode billing berikutnya.',
                'faq_payment_q' => 'Metode pembayaran apa saja yang tersedia?',
                'faq_payment_a' => 'Kami menerima pembayaran melalui Credit Card, Virtual Account (BCA, Mandiri, BNI, BRI), GoPay, ShopeePay, dan metode lainnya via Midtrans.',
                'faq_refund_q' => 'Apakah ada garansi uang kembali?',
                'faq_refund_a' => 'Ya, kami memberikan garansi 7 hari uang kembali jika Anda tidak puas dengan layanan kami.',
                
                // Contact Sales
                'need_enterprise' => 'Butuh paket khusus untuk enterprise?',
                'contact_sales_desc' => 'Hubungi tim sales kami untuk mendiskusikan kebutuhan bisnis Anda',
                'contact_sales' => 'Hubungi Sales',
                
                // Password Modal
                'old_password' => 'Password Lama',
                'new_password' => 'Password Baru',
                'confirm_password' => 'Konfirmasi Password',
                
                // Messages
                'preferences_saved' => 'Preferensi berhasil disimpan!',
                'notifications_saved' => 'Pengaturan notifikasi berhasil disimpan!',
                'profile_updated' => 'Profile berhasil diperbarui!',
                'password_changed' => 'Password berhasil diubah!',
                'employee_added' => 'Karyawan berhasil ditambahkan!',
                'employee_updated' => 'Karyawan berhasil diperbarui!',
                'employee_deleted' => 'Karyawan berhasil dihapus!',
                'branch_added' => 'Cabang berhasil ditambahkan!',
                'branch_updated' => 'Cabang berhasil diperbarui!',
                'branch_deleted' => 'Cabang berhasil dihapus!',
                'no_data' => 'Tidak ada data',
                'no_employees' => 'Tidak ada data karyawan',
                'no_branches' => 'Tidak ada cabang',
            ],
            'en' => [
                // General
                'save' => 'Save',
                'cancel' => 'Cancel',
                'edit' => 'Edit',
                'delete' => 'Delete',
                'add' => 'Add',
                'search' => 'Search',
                'loading' => 'Loading...',
                'success' => 'Success',
                'error' => 'Error',
                'warning' => 'Warning',
                'confirm' => 'Confirm',
                'yes' => 'Yes',
                'no' => 'No',
                'view_all' => 'View All',
                'filter' => 'Filter',
                'export' => 'Export',
                'print' => 'Print',
                'download' => 'Download',
                'back' => 'Back',
                'next' => 'Next',
                'previous' => 'Previous',
                'detail' => 'Detail',
                'view' => 'View',
                'close' => 'Close',
                'date' => 'Date',
                'time' => 'Time',
                'month' => 'Month',
                'year' => 'Year',
                'total' => 'Total',
                'amount' => 'Amount',
                'price' => 'Price',
                'quantity' => 'Quantity',
                'description' => 'Description',
                'notes' => 'Notes',
                'address' => 'Address',
                'active' => 'Active',
                
                // Sidebar Menu
                'dashboard' => 'Dashboard',
                'orders' => 'Orders',
                'inventory' => 'Inventory',
                'customers' => 'Customers',
                'finance' => 'Finance',
                'recommendations' => 'Recommendations',
                'settings' => 'Settings',
                'logout' => 'Logout',
                
                // Dashboard Page
                'welcome_back' => 'Welcome Back',
                'total_revenue' => 'Total Revenue',
                'total_orders' => 'Total Orders',
                'total_orders_today' => 'Total Orders Today',
                'monthly_revenue' => 'Monthly Revenue',
                'from_last_month' => 'from last month',
                'active_customers' => 'Active Customers',
                'pending_pickups' => 'Pending Pickups',
                'requires_attention' => 'Requires attention',
                'branch_performance' => 'Branch Performance',
                'customer_volume_service' => 'Customer Volume Per Service',
                'monthly_revenue_trend' => 'Monthly Revenue Trend',
                'service_distribution' => 'Service Distribution',
                'recommendation' => 'Recommendation',
                'view_details' => 'View Details',
                'total_customers' => 'Total Customers',
                'total_products' => 'Total Products',
                'recent_orders' => 'Recent Orders',
                'no_recent_orders' => 'No recent orders',
                'customer' => 'Customer',
                'service' => 'Service',
                'revenue_chart' => 'Revenue Chart',
                'today' => 'Today',
                'this_week' => 'This week',
                'this_month' => 'This month',
                'this_year' => 'This year',
                'order_id' => 'Order ID',
                'customer_name' => 'Customer Name',
                'notifications_alerts' => 'Notifications & Alerts',
                'mark_all_read' => 'Mark All as Read',
                'quick_actions' => 'Quick Actions',
                'add_order' => 'Add Order',
                'add_customer' => 'Add Customer',
                
                // Orders Page
                'order_list' => 'Order List',
                'new_order' => 'New Order',
                'order_status' => 'Order Status',
                'pending' => 'Pending',
                'processing' => 'Processing',
                'completed' => 'Completed',
                'cancelled' => 'Cancelled',
                'order_date' => 'Order Date',
                'delivery_date' => 'Delivery Date',
                'payment_status' => 'Payment Status',
                'paid' => 'Paid',
                'unpaid' => 'Unpaid',
                'partial' => 'Partial',
                
                // Inventory Page
                'manage_inventory' => 'Manage Inventory',
                'product_list' => 'Product List',
                'add_product' => 'Add Product',
                'product_name' => 'Product Name',
                'item_id' => 'Item ID',
                'item_name' => 'Item Name',
                'stock' => 'Stock',
                'stock_qty' => 'Stock Qty',
                'unit' => 'Unit',
                'last_stock' => 'Last Stock',
                'supplier' => 'Supplier',
                'low_stock' => 'Low Stock',
                'out_of_stock' => 'Out of Stock',
                'available' => 'Available',
                'category' => 'Category',
                'all_categories' => 'All Categories',
                'material' => 'Material',
                'tools' => 'Tools',
                'supplies' => 'Supplies',
                'top_item_usage' => 'Top Item Usage',
                'inventory_by_category' => 'Inventory by Category',
                'stock_trend' => 'Stock Trend',
                'sku' => 'SKU',
                'cost_price' => 'Cost Price',
                'selling_price' => 'Selling Price',
                'stock_alert' => 'Stock Alert',
                'no_inventory_data' => 'No inventory data',
                
                // Customers Page
                'customer_list' => 'Customer List',
                'add_customer' => 'Add Customer',
                'customer_id' => 'Customer ID',
                'total_transactions' => 'Total Transactions',
                'last_order' => 'Last Order',
                'customer_since' => 'Customer Since',
                
                // Finance Page
                'financial_report' => 'Financial Report',
                'income' => 'Income',
                'expense' => 'Expense',
                'profit' => 'Profit',
                'loss' => 'Loss',
                'balance' => 'Balance',
                'transaction_history' => 'Transaction History',
                'total_income' => 'Total Income',
                'total_expense' => 'Total Expense',
                'net_profit' => 'Net Profit',
                'current_period' => 'Current Period',
                'transactions' => 'Transactions',
                'cash_flow_trend' => 'Cash Flow Trend',
                'expense_breakdown' => 'Expense Breakdown',
                'cost_details' => 'Cost Details',
                'add_transaction' => 'Add Transaction',
                'add_income' => 'Add Income',
                'add_expense' => 'Add Expense',
                'export_data' => 'Export Data',
                'report_type' => 'Report Type',
                'all_transactions' => 'All Transactions',
                'income_only' => 'Income Only',
                'expense_only' => 'Expense Only',
                'other_format' => 'Other Formats',
                'for_print' => 'For Print',
                'filter_finance' => 'Filter Finance',
                'apply_filter' => 'Apply Filter',
                'reset' => 'Reset',
                'all_branches' => 'All Branches',
                'all_months' => 'All Months',
                'transaction_name' => 'Transaction Name',
                'type' => 'Type',
                'no_transaction_data' => 'No transaction data',
                'transaction_proof' => 'Transaction Proof',
                
                // Customer Page
                'manage_customers' => 'Manage Customers',
                'total_customers' => 'Total Customers',
                'active_customers' => 'Active Customers',
                'new_this_month' => 'New This Month',
                'all_time' => 'All Time',
                'last_30_days' => 'Last 30 Days',
                'distribution_by_branch' => 'Distribution by Branch',
                'top_active_customers' => 'Top 5 Active Customers',
                'monthly_growth' => 'Monthly Growth',
                'customer_data' => 'Customer Data',
                'add_customer' => 'Add Customer',
                'search_customer' => 'Search customer...',
                'total_orders' => 'Total Orders',
                'add_new_customer' => 'Add New Customer',
                'customer_details' => 'Customer Details',
                'confirm_delete' => 'Confirm Delete',
                'confirm_delete_customer' => 'Are you sure you want to delete customer:',
                'no_customer_data' => 'No customer data',
                'months_6' => '6 Months',
                'months_3' => '3 Months',
                'months_12' => '12 Months',
                
                // Orders Page
                'manage_orders' => 'Manage Orders',
                'order_list' => 'Order List',
                'new_order' => 'New Order',
                'pending_orders' => 'Pending Orders',
                'in_process' => 'In Process',
                'ready_pickup' => 'Ready for Pickup',
                'order_details' => 'Order Details',
                'order_date' => 'Order Date',
                'pickup_date' => 'Pickup Date',
                'service_type' => 'Service Type',
                'shoe_type' => 'Shoe Type',
                'shoe_brand' => 'Shoe Brand',
                'order_notes' => 'Order Notes',
                'update_status' => 'Update Status',
                'print_invoice' => 'Print Invoice',
                'no_order_data' => 'No order data',
                'order_data' => 'Order Data',
                'order_number' => 'Order Number',
                'order_trend' => 'Order Trend',
                'orders_by_branch' => 'Orders by Branch',
                'orders_completed' => 'Orders Completed',
                'received' => 'Received',
                'cancelled' => 'Cancelled',
                'quick_insights' => 'Quick Insights',
                'days' => 'Days',
                'all_status' => 'All Status',
                'will_be_deleted' => 'will be permanently deleted',
                
                // Recommendations Page
                'ai_recommendations' => 'AI Recommendations',
                'product_recommendations' => 'Product Recommendations',
                'sales_insights' => 'Sales Insights',
                'inventory_suggestions' => 'Inventory Suggestions',
                
                // Settings Page
                'profile_settings' => 'Profile Settings',
                'manage_profile_preferences' => 'Manage your profile and account preferences',
                'full_name' => 'Full Name',
                'email' => 'Email',
                'phone' => 'Phone',
                'password' => 'Password',
                'change_password' => 'Change Password',
                'change_photo' => 'Change Photo',
                'save_changes' => 'Save Changes',
                
                // Employee Management
                'manage_employees' => 'Manage Employee Accounts',
                'manage_employees_desc' => 'Add and manage staff accounts for your branches',
                'add_employee' => 'Add Employee Account',
                'employee_id' => 'Employee ID',
                'employee_name' => 'Employee Name',
                'position' => 'Position',
                'branch' => 'Branch',
                'status' => 'Status',
                'action' => 'Action',
                'active' => 'Active',
                'inactive' => 'Inactive',
                
                // Branch Management
                'manage_branches' => 'Manage Business Branches',
                'add_branch' => 'Add Branch',
                'branch_name' => 'Branch Name',
                'address' => 'Address',
                
                // Notification Settings
                'notification_settings' => 'Notification Settings',
                'order_updates' => 'Order Updates',
                'order_updates_desc' => 'Get notified when orders are placed or updated',
                'inventory_stock' => 'Inventory Stock',
                'inventory_stock_desc' => 'Get alerts when stock is running low',
                'daily_report' => 'Daily Report',
                'daily_report_desc' => 'Receive daily report summary via email',
                
                // System Preferences
                'system_preferences' => 'System Preferences',
                'language' => 'Language',
                'currency' => 'Currency',
                'save_preferences' => 'Save Preferences',
                
                // Subscription
                'upgrade_subscription' => 'Upgrade Subscription',
                'upgrade_desc' => 'Unlock premium features to grow your business',
                'current_plan' => 'Current plan',
                'view_packages' => 'View Packages',
                
                // Subscription Page
                'choose_subscription' => 'Choose Subscription Plan',
                'upgrade_business' => 'Upgrade your business with premium features',
                'active_plan' => 'Active Plan',
                'valid_until' => 'Valid until',
                'free_plan' => 'Free',
                'pro_plan' => 'Pro',
                'premium_plan' => 'Premium',
                'free_forever' => 'Free Forever',
                'per_month' => 'Month',
                'perfect_small_business' => 'Perfect for small businesses',
                'ideal_growing_business' => 'Ideal for growing businesses',
                'for_enterprise' => 'For enterprise businesses',
                'most_popular' => 'Most Popular',
                'get_started' => 'Get Started',
                'up_to_orders' => 'Up to {0} orders/month',
                'orders_100' => 'Up to 100 orders/month',
                'orders_10000' => 'Up to 10,000 orders/month',
                'unlimited_orders' => 'Unlimited orders',
                'basic_inventory' => 'Basic inventory tracking',
                'email_support' => 'Email support',
                'advanced_analytics' => 'Advanced analytics',
                'ai_recommendations' => 'AI recommendations',
                'priority_support' => 'Priority support',
                'custom_integrations' => 'Custom integrations',
                'multi_location' => 'Multi-location support',
                'phone_support_24_7' => '24/7 phone support',
                
                // FAQ Section
                'faq_title' => 'Frequently Asked Questions',
                'faq_upgrade_q' => 'How do I upgrade my plan?',
                'faq_upgrade_a' => 'Click the upgrade button on the plan you want, then follow the payment process. Your subscription will be active immediately after successful payment.',
                'faq_downgrade_q' => 'Can I downgrade my plan?',
                'faq_downgrade_a' => 'Yes, you can downgrade at any time. Changes will take effect in the next billing period.',
                'faq_payment_q' => 'What payment methods are available?',
                'faq_payment_a' => 'We accept payments via Credit Card, Virtual Account (BCA, Mandiri, BNI, BRI), GoPay, ShopeePay, and other methods via Midtrans.',
                'faq_refund_q' => 'Is there a money-back guarantee?',
                'faq_refund_a' => 'Yes, we offer a 7-day money-back guarantee if you are not satisfied with our service.',
                
                // Contact Sales
                'need_enterprise' => 'Need a custom enterprise package?',
                'contact_sales_desc' => 'Contact our sales team to discuss your business needs',
                'contact_sales' => 'Contact Sales',
                
                // Password Modal
                'old_password' => 'Old Password',
                'new_password' => 'New Password',
                'confirm_password' => 'Confirm Password',
                
                // Messages
                'preferences_saved' => 'Preferences saved successfully!',
                'notifications_saved' => 'Notification settings saved successfully!',
                'profile_updated' => 'Profile updated successfully!',
                'password_changed' => 'Password changed successfully!',
                'employee_added' => 'Employee added successfully!',
                'employee_updated' => 'Employee updated successfully!',
                'employee_deleted' => 'Employee deleted successfully!',
                'branch_added' => 'Branch added successfully!',
                'branch_updated' => 'Branch updated successfully!',
                'branch_deleted' => 'Branch deleted successfully!',
                'no_data' => 'No data available',
                'no_employees' => 'No employee data',
                'no_branches' => 'No branches available',
            ]
        ];
    }
}

if (!function_exists('get_current_lang')) {
    /**
     * Get current language code
     * @return string
     */
    function get_current_lang() {
        $CI =& get_instance();
        return $CI->session->userdata('bahasa') ?? 'id';
    }
}
